services:
  mysql:
    image: mysql:latest
    container_name: sks_db
    restart: always
    env-file: ".env"
    ports:
      - "3306:3306"
    volumes:
      - schedule_data:/var/lib/mysql

volumes:
  schedule_data:
