services:
  mysql:
    image: mysql:latest
    container_name: sks_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: sks
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - schedule_data:/var/lib/mysql

volumes:
  schedule_data:
